### ISSUE TITLE
Hash of the clipboard

### ISSUE THREAD

**Issue by aaomidi** [Zyncco/Specs#2]
The hash should be md5:
- There is no attack vector in this.
- MD5 is much faster, both in generation and equality checking (its smaller).
- Less storage needed from Google Cloud.

**Comment by aaomidi** [comment]
Although SHA1 could be faster, it should be considered too. SHA256 is definitely slower though.

**Comment by aaomidi** [comment]
CRC32 could work as well.

@mkotb can you do a test of these?

**Comment by aaomidi** [comment]
I actually vote for CRC32, MD5 isn't available through WebCrypto (Stupid decision imo). We don't need security, just error checking.

@BranicYeti can you do a test comparing CRC32 and SHA1 on JS?

**Comment by mkotb** [comment]
I would vote for CRC32, as it was intentionally designed to detect unintentional changes in data. It is also much more efficient (due to the fact that it's much less complex) and less straining. It is a lot more compatible across platforms, it even works on embedded systems.

**Comment by aaomidi** [comment]
This being the majority of people who wanted to vote. CRC32 is decided to be used.

@Vilsol as you're updating the specs, close this issue when you're done <3

**Comment by aaomidi** [comment]
Alright so, this was a terrible idea and was basically the equivalent of rolling our own encryption out.
Proper model, I think at least:

1. Encrypt the data and then hash the encryption (again with CRC32). That is now the hash we send in the json.
3. @Vilsol specific, store the length of payload too. When checking for duplicate, check for length first it'll handle 99% of cases. If its the same, then check for the hash value.

The server should know nothing about the decrypted version of the data other than the MIME(Image, Video, Text, Binary) type.

**Comment by Zenexer** [comment]
1. The only knowledge the server should have about the input is the encrypted output.  Any metadata (MIME type, file permissions, etc.) need to be included in the input to the encryption function; metadata shouldn't be encrypted/stored separately, except perhaps in the case of tags, if you eventually decide to save and organize snippets.  (That's out of scope for the time being, if I understand correctly, and significantly complicates the security model.)
2. Store the length of the encrypted output.  This will be handy, and permits quickly ruling out duplicates.
3. Outsource as much work as possible to the client.  This includes hashing the encrypted output (**not** the input) and checking duplicates.
4. When a client checks for a duplicates:
    1. Compare sizes -> fastest, rules out most
    2. Compare CRC32 hashes -> fast, rules out most
    3. Compare encrypted output byte-for-byte up to *n* bytes -> you can do this as you encrypt it or as you hash it with negligible increase on time and no increase in time complexity, except when comparing two separate files from a hard drive (as opposed to one being in memory) due to seek delays

The seek issue in 4.iii can be avoided easily by keeping a sufficient buffer in memory, which should be trivial.

**Comment by Zenexer** [comment]
> There is no attack vector in this.

There's a potential vulnerability, the severity of which can't easily be assessed, whenever two distinct algorithms are used on the input (e.g., hash + encryption).  Even if you were to include the hash in the encrypted input like this:

    encrypt(input + hash(input))

...you'd still be introducing a potential vulnerability that couldn't be assessed.  Such vulnerabilities have been found and demonstrated to be practice in some SSL/TLS implementations of AES-CBC.

**Comment by aaomidi** [comment]
I would argue that type of the clipboard shouldn't be encrypted. We need that information for metrics and for clients to decide what type of status they want to sync down (receive).

**Comment by mkotb** [comment]
@aaomidi We can encrypt the metadata separate from the data, and send the encrypted metadata over Firebase; allowing the client to make the decision on whether to accept it or not based on the metadata they encrypted with their local key.

**Comment by aaomidi** [comment]
It still doesn't solve the metrics problem.

**Comment by mkotb** [comment]
@aaomidi then we aren't really zero-knowledge... A malicious server could end up playing with the metadata

**Comment by aaomidi** [comment]
I'd rather us keep the Meta data. We need to see what stuff our clients are using more and how they're being handled. We could change this decision on future releases.

**Comment by Zenexer** [comment]
If you have access to the metadata, it's not zero-knowledge.

**Comment by aaomidi** [comment]
Oh well. For metrics we're keeping it at least during the beta.

**Comment by Zenexer** [comment]
That's fine, but you can't advertise your application as being zero-knowledge.

**Comment by aaomidi** [comment]
"Our application knows nothing about your clipboard or the content other than the generic type. Simply we will only know if it is text, picture, video, or a generic file type."

**Comment by Zenexer** [comment]
Remember, you can have users opt in to sending metrics separately.

**Comment by aaomidi** [comment]
For the beta release I'd rather get metrics from everyone. This will be clear in the terms of the beta program.

**Comment by Zenexer** [comment]
There's more metadata than that. What about filename? Permissions?

**Comment by aaomidi** [comment]
We don't care about the other meta data. Just file type.

To clarify, this is only the generic type in each. For example, if its an image we don't know if its PNG or JPEG. We just know that it's an "image".

**Comment by aaomidi** [comment]
There is also a bunch of other information that we're going to get no matter what, such as timestamps and who is sending a clipboard.

**Comment by Zenexer** [comment]
Timestamp should be encrypted. You only need to store the order.

**Comment by aaomidi** [comment]
We're only keeping the past 10 records on the server. A plaintext timestamp helps us with the logic immensely.

We'll figure out something if people are worried about that in later updates to the API.

**Comment by Zenexer** [comment]
I don't see how a timestamp helps you once consistency is established.

**Comment by aaomidi** [comment]
Encrypting timestamps doesn't really make sense. Its security by obfuscation (at least I think it is), since the server still knows when it got a specific entry.

I don't really see anything gained from encrypting that. Honestly @Vilsol should comment on this specifically since I think he does stuff on the server side with this timestamp.

**Comment by Zenexer** [comment]
If someone dumps the database, they won't have timestamps.

**Comment by aaomidi** [comment]
Actually Firebase keeps a track of last login and user creation with timestamps. If database gets leaked that doesn't really help.

**Comment by mkotb** [comment]
To bring back to the original point of this issue, the hashing method is CRC32 and the crypto method (AES256/GCM/NoPadding) already takes care of all this. Closed.
